application:
  actions: actions
  runtimeManifest:
    packages:
      premium-learning:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
          learner-context:
            function: actions/learner-context/index.js
            web: 'no'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              PL_API_BASE: $PL_API_BASE
              PL_API_KEY: $PL_API_KEY
            annotations:
              require-adobe-auth: false
              final: true
          retrieval:
            function: actions/retrieval/index.js
            web: 'no'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              PL_API_BASE: $PL_API_BASE
              PL_API_KEY: $PL_API_KEY
            annotations:
              require-adobe-auth: false
              final: true
